evercode:
  image: orlandoc1618/pt-evercode:v3
  links:
    - redis
    - mongodb
  ports:
    - "3000:3000"

mongodb:
  image: mongo
  ports:
    - "27017" 

redis:
  image: redis
  ports:
    - "6379"
  command: redis-server